# Generated by Django 5.2.1 on 2025-10-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
