# Generated by Django 5.2.1 on 2025-11-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('S', 'Stripe'), ('P', 'PayPal')], max_length=1, null=True),
        ),
    ]
