# Generated by Django 5.2.1 on 2025-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available_colors',
            field=models.CharField(blank=True, choices=[('B', 'Black'), ('R', 'Red'), ('P', 'Paje'), ('W', 'White')], null=True),
        ),
    ]
