# Generated by Django 5.2.1 on 2025-06-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_available_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_colors',
            field=models.CharField(blank=True, null=True),
        ),
    ]
