# Generated by Django 5.2.1 on 2025-06-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_available_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available_colors',
        ),
    ]
