# Generated by Django 5.2.1 on 2025-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_color_item_available_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_colors',
            field=models.ManyToManyField(related_name='item_colors', to='core.color'),
        ),
    ]
