# Generated by Django 5.2.1 on 2025-06-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('core', '0007_alter_item_available_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='checkout.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
