# Generated by Django 5.2.1 on 2025-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Accessories', 'Accessories'), ('Beauty', 'Beauty')], max_length=11),
        ),
    ]
