# Generated by Django 5.2.1 on 2025-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hyper_category',
            field=models.CharField(choices=[('J', 'Jeans'), ('S', 'Shirts'), ('C', 'Coats'), ('JA', 'Jackets'), ('D', 'Dresses'), ('B', 'Bags')], max_length=2),
        ),
    ]
