# Generated by Django 5.2.1 on 2025-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_item_hyper_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('S', 'Sale'), ('O', 'Out of Stock')], max_length=1, null=True),
        ),
    ]
