# Generated by Django 5.2.1 on 2025-10-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='info',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
